apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        image: analytics-service:latest
        imagePullPolicy: Never
        env:
        - name: REDIS_HOST
          value: "redis"
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5002
  selector:
    app: analytics-service