apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortening-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortening-service
  template:
    metadata:
      labels:
        app: shortening-service
    spec:
      containers:
      - name: shortening-service
        image: shortening-service:latest
        imagePullPolicy: Never
        env:
        - name: REDIS_HOST
          value: "redis"
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: shortening-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5001
  selector:
    app: shortening-service